#include "polymorphic_class/any.hpp"
#include "polymorphic_class/function.hpp"
#include "polymorphic_class/optional.hpp"
#include "polymorphic_class/expected.hpp"
#include "polymorphic_class/variant.hpp"